<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-NADE445V" failures="1" tests="1" name="Default test" time="58.85" errors="0" timestamp="2022-09-04T22:28:25 WIB">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="58.386">
    <failure type="java.lang.AssertionError" message="expected [Welcome to your account. Here you can manage all of your personal information and orders.] but found [Welcome to your account. Here you can manage all   of your personal information and orders.]">
      <![CDATA[java.lang.AssertionError: expected [Welcome to your account. Here you can manage all of your personal information and orders.] but found [Welcome to your account. Here you can manage all   of your personal information and orders.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.insignia.test.seleniumgluecodes.Test.success_message_is_displayed(Test.java:39)
at âœ½.success message is displayed(file:///C:/Users/Lenovo/eclipse-workspace/com.insignia.test/src/main/resources/features/ValidLogin.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
